security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto

  providers:
    user_doctrine:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      user_checker: App\Security\UserChecker
      remember_me:
        secure: true
        lifetime: 604800
        secret: '%kernel.secret%'
        path: /
      lazy: true
      provider: user_doctrine
      form_login:
        login_path: security_login
        check_path: security_login
        enable_csrf: true
      logout:
        path: security_logout

  role_hierarchy:
    ROLE_PRODUCER: [ ROLE_USER ]
    ROLE_CUSTOMER: [ ROLE_USER ]

  access_control:
