producers:
  - name: 'Manger Bio 44'
    siret: '51171732400012'
    address: '58 Boulevard Gustave Roch'
    city: 'Nantes'
    postalCode: '44200'
    country: 'France'
    lat: 47.19874794450828
    lng: -1.5530324573306642
    phone: '0982486519'
    region: 'Loire-Atlantique, Pays de la Loire'

  - name: 'Au fil des saisons'
    siret: '51857397700015'
    address: '7 ter rue Saint-Julien'
    city: 'Bouvron'
    postalCode: '44130'
    country: 'France'
    lat: 47.41754397282512
    lng: -1.8472411726672717
    phone: '0240544489'
    region: 'Loire-Atlantique, Pays de la Loire'

  - name: 'GAEC DUREAU'
    siret: '82417079900012'
    address: '203 RUE DES FONTENELLES, LA PRIÈRE, ARTHON-EN-RETZ'
    city: 'CHAUMES-EN-RETZ'
    postalCode: '44320'
    country: 'France'
    lat: 47.13795844203793
    lng: -1.9629351438391731
    phone: '0982486519'
    region: 'Loire-Atlantique, Pays de la Loire'

  - name: 'Graines de Bio'
    siret: '84829997000014'
    address: '5 Place du Champ de foire'
    city: 'Nort-sur-Erdre'
    postalCode: '44390'
    country: 'France'
    lat: 47.436969047317085
    lng: -1.500588872666757
    phone: '0251819072'
    region: 'Loire-Atlantique, Pays de la Loire'

  - name: 'Le Wagon'
    siret: '43903837300015'
    address: 'Les Hauts Roseaux'
    city: 'Pannecé'
    postalCode: '44440'
    country: 'France'
    lat: 47.467990539136146
    lng: -1.2253027303371875
    phone: '0240977852'
    region: 'Loire-Atlantique, Pays de la Loire'

  - name: 'La Ferme de Chez Nous'
    siret: '51045908400024'
    address: '2 Route de la Vendée'
    city: 'Mouzillon'
    postalCode: '44330'
    country: 'France'
    lat: 47.13970893931923
    lng: -1.2817406591816431
    phone: '0228024944'
    region: 'Loire-Atlantique, Pays de la Loire'

  - name: 'Les Fermiers Nantais'
    siret: '80778337800019'
    address: '290 route de Vannes'
    city: 'Orvault'
    postalCode: '44700'
    country: 'France'
    lat: 47.25086826238829
    lng: -1.6166029150005088
    phone: '0240592641'
    region: 'Loire-Atlantique, Pays de la Loire'
